# Generated by Django 2.0.5 on 2018-05-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='stu',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
